### ISSUE TITLE
Start image not `background-size: cover;` - black bars on bigger/wider displays.

### ISSUE THREAD

**Issue by mhsdesign** [neos/Neos.Demo#143]
Ive never come around reporting it, but look :P

![image](https://user-images.githubusercontent.com/85400359/180179246-a9ad0269-a6f4-4c8f-a77a-30cfb033c0b9.png)

i guess the black bars are not on purpose ... `

(you need a wide screen to reproduce it, or just make the window wider ^^)

```css
.main-header.image {
    background-size: cover;
}
```
